export {default as Button} from './Button/Button'
export {default as Title} from './Title/Title'
export {default as Container} from'./Container/Container'
export {default as Content} from'./Content/Content'
export {default as Card} from'./Card/Card'
export {default as Input} from'./Input/Input'
export {default as Slider} from'./Slider/Slider'